import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";

// POST /api/messages - Send a message to AI
export async function POST(req: NextRequest) {
  try {
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await req.json();
    const { conversationId, content, projectId } = body;

    if (!content) {
      return NextResponse.json(
        { error: "Content is required" },
        { status: 400 }
      );
    }

    // TODO: Implement actual AI integration with Gemini 2.0 Flash
    // For now, return a placeholder response

    // Store user message in Convex
    // TODO: Call Convex mutation to store message

    // Call AI API
    // TODO: Implement Gemini API call

    // Store AI response in Convex
    // TODO: Call Convex mutation to store response

    return NextResponse.json({
      success: true,
      message: {
        id: Date.now().toString(),
        role: "assistant",
        content:
          "This is a placeholder response. In production, this would be generated by Gemini 2.0 Flash based on your message and project context.",
        timestamp: new Date().toISOString(),
      },
    });
  } catch (error) {
    console.error("Error processing message:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}

// GET /api/messages - Get messages for a conversation
export async function GET(req: NextRequest) {
  try {
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { searchParams } = new URL(req.url);
    const conversationId = searchParams.get("conversationId");

    if (!conversationId) {
      return NextResponse.json(
        { error: "Conversation ID is required" },
        { status: 400 }
      );
    }

    // TODO: Fetch messages from Convex

    return NextResponse.json({
      messages: [],
    });
  } catch (error) {
    console.error("Error fetching messages:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
